### ISSUE TITLE
AccordionBox title bars have a cursor but are not clickable when closed

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/balancing-chemical-equations#139] opened 2019-01-14 18:16 UTC
For https://github.com/phetsims/QA/issues/237 on any screen with the box areas for reactants and products there is a click box in the top right corner that allows for the boxes to be minimized. When scrolling the cursor over the area to the left of this box (on the top of the box from the edge of the click box to the left hand side of the box area) the cursor changes shape to the hand, indicating that the region can be clicked. The area to the left of the click box does nothing when clicked, making the change in cursor shape only confusing to the user. I have attached screenshots of the sim with the showPointerAreas query parameter to illustrate the problem however the cursor has disappeared from the screenshots. To replicate the issue simply place the cursor to the left of the concentric red and blue pointer areas in the top right of the reactants and products box areas.
![screen shot 2019-01-14 at 11 04 31 am](https://user-images.githubusercontent.com/30352536/51131592-6de62c80-17ed-11e9-9e98-ccdd613a2600.png)
![screen shot 2019-01-14 at 11 06 26 am](https://user-images.githubusercontent.com/30352536/51131595-7179b380-17ed-11e9-988a-56977dedbedc.png)

**Comment by pixelzoom** [comment] 2019-01-14 18:21
@JRomero0613 @KatieWoe This sounds like a duplicate of https://github.com/phetsims/balancing-chemical-equations/issues/125#issuecomment-453632610.  Could you please confirm?

**Comment by KatieWoe** [comment] 2019-01-14 18:23
@pixelzoom yes it is

**Comment by pixelzoom** [comment] 2019-01-15 04:30
To test this in 1.2.0-rc.3, verify that:
(1) there is no cursor when your mouse is over the AccordionBox titlebar
(2) clicking in the AccordionBox titlebar does nothing

**Comment by KatieWoe** [comment] 2019-01-15 17:14
1.2.0-rc.2 looks good on Win 10 chrome

**Closed by KatieWoe** 2019-01-15 17:14 UTC
Labels: status:fixed-pending-testing, type:bug
