### ISSUE TITLE
hasBigMolecule always returns false

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-chemical-equations#147] opened 2021-04-06 21:56 UTC
Discovered in https://github.com/phetsims/chipper/issues/1033.  Equation.js has this function:

```js
  hasBigMolecule() {
    this.reactants.forEach( reactant => {
      if ( reactant.molecule.isBig() ) {
        return true;
      }
    } );
    this.products.forEach( product => {
      if ( product.molecule.isBig() ) {
        return true;
      }
    } );
    return false;
  }
```

Note that this function always returns `false`.  This means the use cases in RandomStrategy are incorrect:

```js
      // If the first equation isn't supposed to contain any "big" molecules,
      // then find an equation in the pool that has no big molecules.
      if ( i === 0 && !this.firstBigMolecule && factoryFunction().hasBigMolecule() ) {
```

and

```js
          if ( !factoryFunction().hasBigMolecule() ) {
            done = true; // success, this equation has no big molecules
          }
```

Assigning to the responsible-dev for the simulation.  After this is fixed, we should consider whether a new release or maintenance release is warranted.

**Comment by pixelzoom** [comment] 2021-04-06 23:01
This sim was ported by MLL in 2014, and I inherited it because I was the Java developer.  That said...

I confirmed that the `hasBigMolecule ` method identified by @samreid above is buggy.  Returning from`forEach` is incorrect, and the method always returns `false`.

This is definitely affecting the section of challenges in the game, so that's it's not behaving as desired.  My guess is that it's choosing some difficult challenges that involve "big" molecules, when it should be selecting less-difficult challenges that only involve "small" molecules. 

Unfortunately, fixing this is not as simple as rewriting the `hasBigMolecule` method.  When I tried that, the sim runs code that has never been reachable (and therefore never tested), and it fails hard.   So this is going to be at least a couple of hours to fix, possible more.  Then we'll undoubtedly want to patch the 1.2 (production) branch and deploy a ne wproduction version.  The 1.2 branch is quite old (pre-ES6) so patching it will not be a simple cherry-pick.

The lead designer for this sim is no longer with PhET, so assigning to @kathy-phet.  How would you like to proceed? And who should be the contact for lead designer?

**Comment by pixelzoom** [comment] 2021-04-22 21:58
@arouinfar is taking over as lead designer.  Let me know how you'd like to prioritize, and how you'd like to proceed.

**Comment by pixelzoom** [comment] 2023-02-18 19:34
Unassigning until work resumes on this sim.

**Comment by pixelzoom** [comment] 2024-07-10 18:54
It looks like this was addressed when the sim was converted to TypeScript in https://github.com/phetsims/balancing-chemical-equations/commit/a74a019dc32b3f382e10510778fb7783225e6896.  The implemention of `hasBigMolecule` is now:

```ts
  public hasBigMolecule(): boolean {
    return !!_.find( this.reactants, reactant => reactant.molecule.isBig() ) ||
           !!_.find( this.products, product => product.molecule.isBig() );
  }
```

No problems noted when fuzz testing. So I'll label this as "fixed-awaiting-deploy", to be verified the next time a release branch is to be created for this sim.

**Comment by pixelzoom** [comment] 2024-08-09 16:01
To test this fix...  In Level 1 of the Game, the first challenge should never contain a "big" molecule, which is any molecule with _more than_ 5 atoms.  There is currently no automated way to verify this; you'll need to play level 1 many times and inspect the first challenge.

**Comment by pixelzoom** [comment] 2024-11-07 00:56
In https://github.com/phetsims/balancing-chemical-equations/commit/b36855c7c533509e4bb94bbfbe9bf51604398060, I added `?verifyGame`.  At startup, this creates 1000 equation sets for each game level, and (with assertions enabled) verifies that they meet constraints like the "big molecule" constraint.    After completing each level, it prints to the console, like this:

> Level 1 has been verified using 1000 iterations.
> Level 2 has been verified using 1000 iterations.
> Level 3 has been verified using 1000 iterations.

I'll leave this issue open for QA to verify during dev testing. But after starting the sim 10 times (creating 10,000 equation sets) I'm confident that Level 1 will not have a big molecule as the first challenge.

**Comment by pixelzoom** [comment] 2024-11-07 00:59
To verify in dev testing... Run with `?ea&verifyGame`.  Verify that there are no assertion failures, and the browser console reports:

> Level 1 has been verified using 1000 iterations.
> Level 2 has been verified using 1000 iterations.
> Level 3 has been verified using 1000 iterations.

If you want to manually inspect the first challenge in Level 1, go for it.  Press the "Level 1", inspect the display challenge, press the "Start Over" button, repeat.

**Comment by KatieWoe** [comment] 2024-11-11 21:59
This has a big molecule on the right side? Is it only looking on the left?
![c2h6](https://github.com/user-attachments/assets/2c71f331-3b21-452d-8cba-fb826d0762be)

**Comment by KatieWoe** [comment] 2024-11-11 22:04
I misread this issue I think. This is in level one, but not the first challenge of level 1, so this is probably ok?

**Comment by KatieWoe** [comment] 2024-11-11 22:14
I ran with the querry parameter and things looked ok there. If the rule only applies to the first challenge of level 1 then I think this is good.

**Comment by pixelzoom** [comment] 2024-11-12 00:01
Correct, the rule only applied to the first challenge of level 1.  So I'll consider this issue verified, and close it.

**Closed by pixelzoom** 2024-11-12 00:01 UTC
Labels: type:bug, status:ready-for-review
