### ISSUE TITLE
Moving timer when stringTest=double

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-chemical-equations#136] opened 2018-12-11 23:14 UTC
Test device:
Dell Laptop
Operating System:
Win 10
Browser:
chrome
Problem description:
For https://github.com/phetsims/QA/issues/237
When stringTest=double, the timer shifts text when the timer reads 11 seconds, and then shifts back when it is 12 seconds.  This is likely a very minor issue, but documenting here.
Steps to reproduce:
1. Set stringTest=double
2. Go to the game screen and turn on the timer
3. Start a game and watch the timer until it is about 20 seconds, while observing any shift in text.

Screenshots:
![elevenseconds](https://user-images.githubusercontent.com/41024075/49836431-e6298000-fd5f-11e8-8662-89b9808e5cd7.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Balancing Chemical Equations‬:‪Balancing Chemical Equations‬
URL: https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.1/phet/balancing-chemical-equations_en_phet.html?stringTest=double
Version: 1.2.0-rc.1 2018-12-10 21:21:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"73e761ec","branch":"HEAD"},"balancing-chemical-equations":{"sha":"9e0cd1eb","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"d1c4844e","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"joist":{"sha":"5a013a46","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"422275fd","branch":"HEAD"},"phet-io":{"sha":"a267fdb1","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"29569397","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"e4f9e8e8","branch":"HEAD"},"scenery":{"sha":"80afaf2f","branch":"HEAD"},"scenery-phet":{"sha":"3bcbf357","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"d8dfa60b","branch":"HEAD"},"tambo":{"sha":"ee53ff03","branch":"HEAD"},"tandem":{"sha":"c7a56e2e","branch":"HEAD"},"vegas":{"sha":"9b35cba0","branch":"HEAD"},"vibe":{"sha":"474ae764","branch":"HEAD"}}

</details>

**Comment by pixelzoom** [comment] 2018-12-12 20:44
This is a general issue with `VEGAS/FiniteStatusBar`, and possibly `VEGAS/ElapsedTimeNode` (which displays the clock) and `VEGAS/GameTimer` (which formats the time).   In practice, time strings will never be doubled.  But for some reason, GameTimer uses a translatable string pattern for the time format.   I'll take a brief look at this, but won't spend much time on.   If it's easily solved, I'll do so.  Otherwise I'll move this issue to the vegas repo.

**Comment by pixelzoom** [comment] 2018-12-12 23:46
I could not reproduce on macOS 10.11.6 + Chrome 71.  But I did reproduce on macOS 10.11.6 + Safari 11.

**Comment by pixelzoom** [comment] 2018-12-12 23:50
Also reproduced in other sims that use FiniteStatusBar -- e.g. RPAL.

**Comment by pixelzoom** [comment] 2018-12-12 23:51
I verified that there is no movement of the time displayed _without_ `stringTest=double`.

**Comment by pixelzoom** [comment] 2018-12-12 23:52
@arouinfar I don't see any reason to address this for 1.2 release.  My recommendation is to move this to an issue in the vegas repo.   Do you agree?

**Comment by arouinfar** [comment] 2018-12-13 00:09
> @arouinfar I don't see any reason to address this for 1.2 release. My recommendation is to move this to an issue in the vegas repo. Do you agree?

Agreed @pixelzoom. 👍

**Comment by pixelzoom** [comment] 2018-12-13 17:09
This issue will not be addressed in 1.2 release, and I've moved it to vegas: https://github.com/phetsims/vegas/issues/76

**Closed by pixelzoom** 2018-12-13 17:09 UTC
Labels: type:i18n
