### ISSUE TITLE
Scale icon is poorly rendered Win 8.1/ IE11 & FF31

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balancing-chemical-equations#90] opened 2014-07-24 21:04 UTC
The Scale icon under "Tools:" is poorly rendered. Could be related to small screen size.
![11](https://cloud.githubusercontent.com/assets/5631059/3694803/109b1a3e-1376-11e4-9bb1-9e42fc48be84.png)

Troubleshooting information (do not edit): From IE 11
Name: Balancing Chemical Equations
URL: http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.0.0-dev.15/balancing-chemical-equations_en.html
Version: 1.0.0-dev.15
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS; rv:11.0) like Gecko
Language: en-US
Window: 1093x538
Pixel Ratio: 1.25/1
WebGL: WebGL 0.93
GLSL: WebGL GLSL ES 0.93
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 14 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by pixelzoom** [comment] 2015-05-26 16:38
Consider using the new mipmap feature for the scale image.

**Comment by pixelzoom** [comment] 2015-08-25 21:49
Tested with mipmap and it's better, but still a little jaggy. scales.png will need to be saved at a larger size.

**Comment by pixelzoom** [comment] 2015-08-25 21:57
I doubled the size of scales.png and it still looks crappy. The diagonal lines are problematic.

Before:

![screenshot_581](https://cloud.githubusercontent.com/assets/3046552/9480705/da67f72a-4b41-11e5-8cff-f6615806d8ae.png)

After:

![screenshot_582](https://cloud.githubusercontent.com/assets/3046552/9480704/d742d2c2-4b41-11e5-9f82-ce1b11e79243.png)

**Comment by pixelzoom** [comment] 2015-09-01 15:42
The problem is mainly the diagonal line in the image. Perhaps there's some "Save As" setting in Illustrator that I'm not familiar with.

@jonathanolson Can you suggest how to make this look better?

**Comment by jonathanolson** [comment] 2015-09-01 16:22
The normal size "scales.png" looks really rough, AND includes what looks like a white aliased outline along the outsides, which definitely seems to be the issue.
![screen shot 2015-09-01 at 10 21 20 am](https://cloud.githubusercontent.com/assets/480878/9609840/39cf5e78-5093-11e5-972c-b44e8bdc5207.png)

I can test some ways to export from Illustrator once I'm back at home (no space for a copy on this laptop).

**Comment by pixelzoom** [comment] 2015-09-01 20:42
Thanks @jonathanolson, that would be great if you could take a look. Assigning to you, kick it back to me when you're done.

**Comment by pixelzoom** [comment] 2015-09-08 19:00
@jonathanolson Any thoughts on how to improve this? Not high priority, but it's the last open issue before this sim can be redeployed.

**Comment by jonathanolson** [comment] 2015-09-09 06:33
See the above change, to me it looks good on Win7 IE11/FF.

**Comment by pixelzoom** [comment] 2015-09-10 19:42
Here's what I currently see in Win7+IE11.  It's definitely better, but still jaggy compared to other platforms.

![screenshot_614](https://cloud.githubusercontent.com/assets/3046552/9798940/7835340a-57c1-11e5-9735-8c58253c967d.png)

Compare to Safari:

![screenshot_615](https://cloud.githubusercontent.com/assets/3046552/9798976/a7214c90-57c1-11e5-9013-6a6437ec2d6e.png)

Compare to Mac+Chrome:

![screenshot_616](https://cloud.githubusercontent.com/assets/3046552/9798990/bfb8edda-57c1-11e5-9dff-fd8538e7a3ac.png)

**Comment by pixelzoom** [comment] 2015-09-10 19:43
@jonathanolson is this what you see also? I'm OK with this if that's as good as we think it can be.

**Comment by pixelzoom** [comment] 2015-09-10 19:43
Talked with @jonathanolson, we're going with this.

**Closed by pixelzoom** 2015-09-10 19:43 UTC
Labels: Summer 2015 redeploy
